-- Sample Standard Sizes
INSERT INTO standard_sizes (width, height, depth, volume) VALUES
(50, 30, 20, 30),
(100, 60, 40, 240),
(75, 45, 30, 100),
(25, 20, 15, 7),
(120, 80, 50, 480);

-- Sample Warehouses (you'll need to run this after creating some standard sizes)
-- Note: This is just for reference, actual locations will be generated by the API
-- INSERT INTO warehouse (warehouse_name, created_at, updated_at) VALUES
-- ('Main Distribution Center', NOW(), NOW()),
-- ('North Storage Facility', NOW(), NOW()),
-- ('South Cross-Dock Hub', NOW(), NOW()),
-- ('East Manufacturing Warehouse', NOW(), NOW());